export type DealAssetClass = 'business' | 'real_estate' | 'business_with_real_estate' | 'digital_business' | 'franchise' | 'debt_note' | 'equipment' | 'route_business' | 'mixed_asset' | 'unknown';
export type DealRecommendation = 'strong_pursue' | 'pursue_with_conditions' | 'watch' | 'negotiate_hard' | 'pass' | 'refer_wholesale';
export type VerificationStatus = 'unverified' | 'broker_provided' | 'seller_provided' | 'document_verified' | 'bank_verified' | 'tax_return_verified' | 'estimated' | 'ai_inferred';

export interface CanonicalFact { id: string; deal_id: string; asset_id?: string | null; fact_key: string; fact_value_json: unknown; fact_type: string; unit?: string | null; confidence_score: number; source_document_id?: string | null; source_excerpt?: string | null; verification_status: VerificationStatus; created_by: string; superseded_by_fact_id?: string | null; created_at: string; updated_at: string; }
export interface DealIntelDeal { id: string; title: string; deal_type: string; asset_class: DealAssetClass; status: string; source_type?: string | null; source_url?: string | null; asking_price?: number | null; currency: string; location_summary?: string | null; summary?: string | null; priority: string; owner_user_id: string; dealflow_deal_id?: string | null; empireos_project_id?: string | null; created_at: string; updated_at: string; }
export interface DealIntelAsset { id: string; deal_id: string; asset_type: DealAssetClass; name: string; description?: string | null; address?: string | null; city?: string | null; state?: string | null; country?: string | null; industry?: string | null; operating_status?: string | null; included_in_sale: boolean; created_at: string; updated_at: string; }
export interface SourceDocument { id: string; deal_id: string; document_type: string; title: string; source_url?: string | null; raw_text?: string | null; extracted_text?: string | null; uploaded_by?: string | null; created_at: string; }
export interface DealScore { id: string; deal_id: string; analysis_run_id: string; overall_score: number; probability_of_success: number; risk_score: number; upside_score: number; data_quality_score: number; financing_score: number; operator_fit_score: number; market_score: number; valuation_score: number; exit_score: number; explanation: string; created_at: string; }
export interface DealBrief { deal_id: string; recommendation: DealRecommendation; overall_score: number; probability_of_success: number; executive_summary: string; visual_payload: Record<string, unknown>; next_actions: string[]; missing_information: string[]; }
export interface EmpireOSDealSummary { deal_id: string; title: string; recommendation: DealRecommendation; priority: string; probability_of_success: number; next_best_action: string; due_today: boolean; risk_level: string; potential_value: string; }
export interface DealFlowDealSummary { deal_id: string; buyer_match_recommendation: string; ideal_buyer_types: string[]; deal_brief_status: string; outreach_angle: string; suggested_followups: string[]; }
