-- Deal Intelligence Engine: backend-first source-of-truth schema.
create extension if not exists pgcrypto;

create table if not exists deal_intel_deals (
  id uuid primary key default gen_random_uuid(), title text not null, deal_type text not null default 'acquire', asset_class text not null default 'unknown', status text not null default 'created', source_type text, source_url text, source_contact_id uuid, asking_price numeric, target_price numeric, currency text not null default 'USD', location_summary text, summary text, thesis text, current_stage text, priority text not null default 'medium', owner_user_id uuid not null, empireos_project_id uuid, dealflow_deal_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists deal_intel_assets (id uuid primary key default gen_random_uuid(), deal_id uuid not null references deal_intel_deals(id) on delete cascade, asset_type text not null, name text not null, description text, address text, city text, state text, country text, industry text, naics_code text, operating_status text, ownership_type text, included_in_sale boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists deal_intel_business_profiles (id uuid primary key default gen_random_uuid(), asset_id uuid not null references deal_intel_assets(id) on delete cascade, business_name text, industry text, years_in_business int, employees_count int, owner_role text, reason_for_sale text, lease_status text, lease_expiration date, monthly_rent numeric, hours_of_operation text, customer_concentration_notes text, supplier_concentration_notes text, licenses_required text, transferable_assets text, training_period text, seller_financing_available boolean, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists deal_intel_real_estate_profiles (id uuid primary key default gen_random_uuid(), asset_id uuid not null references deal_intel_assets(id) on delete cascade, property_type text, building_sqft numeric, lot_size numeric, year_built int, units int, occupancy_rate numeric, zoning text, parking_spaces int, current_use text, highest_best_use text, noi numeric, cap_rate numeric, rent_roll_status text, deferred_maintenance_notes text, environmental_risk_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists deal_intel_financial_snapshots (id uuid primary key default gen_random_uuid(), deal_id uuid not null references deal_intel_deals(id) on delete cascade, period_start date, period_end date, revenue numeric, gross_profit numeric, ebitda numeric, sde numeric, noi numeric, operating_expenses numeric, payroll numeric, rent_expense numeric, debt_service numeric, net_income numeric, owner_addbacks numeric, capex_required numeric, working_capital_required numeric, source_quality text, verification_status text not null default 'unverified', created_at timestamptz not null default now());
create table if not exists deal_intel_source_documents (id uuid primary key default gen_random_uuid(), deal_id uuid not null references deal_intel_deals(id) on delete cascade, document_type text not null, title text not null, source_url text, storage_path text, raw_text text, extracted_text text, uploaded_by uuid, received_from_contact_id uuid, document_date date, created_at timestamptz not null default now());
create table if not exists deal_intel_canonical_facts (id uuid primary key default gen_random_uuid(), deal_id uuid not null references deal_intel_deals(id) on delete cascade, asset_id uuid references deal_intel_assets(id) on delete set null, fact_key text not null, fact_value_json jsonb not null, fact_type text not null, unit text, confidence_score numeric not null default 0, source_document_id uuid references deal_intel_source_documents(id) on delete set null, source_excerpt text, verification_status text not null default 'unverified', created_by text not null default 'system', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), superseded_by_fact_id uuid references deal_intel_canonical_facts(id));
create unique index if not exists deal_intel_one_current_fact on deal_intel_canonical_facts(deal_id, coalesce(asset_id, '00000000-0000-0000-0000-000000000000'::uuid), fact_key) where superseded_by_fact_id is null;
create table if not exists deal_intel_evidence_items (id uuid primary key default gen_random_uuid(), deal_id uuid not null references deal_intel_deals(id) on delete cascade, source_document_id uuid references deal_intel_source_documents(id) on delete set null, evidence_type text not null, quote text, url text, page_number int, confidence_score numeric, relevance_score numeric, created_at timestamptz not null default now());
create table if not exists deal_intel_valuation_models (id uuid primary key default gen_random_uuid(), deal_id uuid not null references deal_intel_deals(id) on delete cascade, model_type text not null, input_json jsonb not null default '{}', output_json jsonb not null default '{}', low_value numeric, base_value numeric, high_value numeric, confidence_score numeric, created_at timestamptz not null default now());
create table if not exists deal_intel_deal_scores (id uuid primary key default gen_random_uuid(), deal_id uuid not null references deal_intel_deals(id) on delete cascade, analysis_run_id uuid not null, overall_score int not null, probability_of_success numeric not null, risk_score int, upside_score int, data_quality_score int, financing_score int, operator_fit_score int, market_score int, valuation_score int, exit_score int, explanation text, created_at timestamptz not null default now());
create table if not exists deal_intel_risks (id uuid primary key default gen_random_uuid(), deal_id uuid not null references deal_intel_deals(id) on delete cascade, risk_category text not null, title text not null, description text, severity text not null, likelihood text not null, mitigation text, evidence_item_id uuid references deal_intel_evidence_items(id), status text not null default 'open', created_at timestamptz not null default now());
create table if not exists deal_intel_upside_drivers (id uuid primary key default gen_random_uuid(), deal_id uuid not null references deal_intel_deals(id) on delete cascade, title text not null, description text, upside_type text, estimated_value_impact numeric, difficulty text, timeline text, evidence_item_id uuid references deal_intel_evidence_items(id), created_at timestamptz not null default now());
create table if not exists deal_intel_scenarios (id uuid primary key default gen_random_uuid(), deal_id uuid not null references deal_intel_deals(id) on delete cascade, scenario_name text not null, assumptions_json jsonb not null default '{}', projected_revenue numeric, projected_expenses numeric, projected_cash_flow numeric, projected_roi numeric, projected_equity numeric, exit_value numeric, risk_notes text, created_at timestamptz not null default now());
create table if not exists deal_intel_research_runs (id uuid primary key default gen_random_uuid(), deal_id uuid not null references deal_intel_deals(id) on delete cascade, research_type text not null, status text not null default 'queued', priority text not null default 'normal', started_at timestamptz, completed_at timestamptz, summary text, error_message text, created_at timestamptz not null default now());
create table if not exists deal_intel_agent_runs (id uuid primary key default gen_random_uuid(), deal_id uuid references deal_intel_deals(id) on delete cascade, agent_name text not null, task_type text not null, input_json jsonb not null default '{}', output_json jsonb not null default '{}', status text not null default 'queued', confidence_score numeric, tokens_used int, started_at timestamptz, completed_at timestamptz, error_message text);
create table if not exists deal_intel_diligence_tasks (id uuid primary key default gen_random_uuid(), deal_id uuid not null references deal_intel_deals(id) on delete cascade, title text not null, description text, category text, priority text not null default 'medium', status text not null default 'open', assigned_to uuid, due_date date, linked_fact_id uuid references deal_intel_canonical_facts(id), created_at timestamptz not null default now());
create table if not exists deal_intel_analysis_reports (id uuid primary key default gen_random_uuid(), deal_id uuid not null references deal_intel_deals(id) on delete cascade, analysis_run_id uuid not null, report_type text not null, title text not null, executive_summary text, full_report_markdown text, visual_payload_json jsonb not null default '{}', recommendation text not null, confidence_score numeric, created_at timestamptz not null default now());
